#+title: FIN 411:  Event Study
#+author: Matt Brigida, Ph.D.
#+email: matthew.brigida@sunypoly.edu
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup


#+BEGIN_COMMENT
Case involves having an analyst calculate the abnormal returns for stocks over some event.  Highlights the necessity to calculate what we would expect to happen had the event not occurred.
#+END_COMMENT

* Background

You are an analyst at a large commercial bank, and it is a week after the outbreak of the COVID-19 pandemic. Management obviously wants to cut back on lending, however also wants to identify industries where the bank can gain market share. 

* Problem

You suspect that the COVID-19 crisis had a larger negative impact on certain sectors of the economy, particularly energy.  Alternatively, other sectors may not have been as adversely impacted.  How are you going to test your hypothesis?

* Analysis

You can use any tool you want to calculate abnormal returns.  See this Colab notebook for a implementation in Python:  

